//created on: Jan 3, 2014
package com.acme.insurance.policyquote

//list any import classes here.
import org.acme.insurance.Driver
import org.acme.insurance.Policy

rule "SafeAdults"

    ruleflow-group "calculation"

    when
        //conditions
        driver : Driver(age > 24, numberOfAccidents < 1, numberOfTickets <= 1)
        policy : Policy(price == 0, policyType == "AUTO")
    then
        //actions
        modify(policy) {setPrice(120)};

end

